DROP TABLE IF EXISTS diseasemedicines;
DROP TABLE IF EXISTS symptomdiseases;
DROP TABLE IF EXISTS usersymptoms;
DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS medicines;
DROP TABLE IF EXISTS diseases;
DROP TABLE IF EXISTS symptoms;
DROP TABLE IF EXISTS hospitals;
DROP TABLE IF EXISTS doctors;
DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS symptomtests;

